
-----------------
-- Vertex Type --
-----------------

-- Table
CREATE TABLE GRESTLER_VERTEX_TYPE (
    ID UUID NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    SUPER_TYPE_ID UUID NOT NULL
);

-- Primary key
ALTER TABLE GRESTLER_VERTEX_TYPE ADD CONSTRAINT PK_GRESTLER_VERTEX_TYPE
    PRIMARY KEY (ID);

-- Foreign keys
ALTER TABLE GRESTLER_VERTEX_TYPE ADD CONSTRAINT FK_GRESTLER_VERTEX_TYPE__SUPER_TYPE
    FOREIGN KEY (SUPER_TYPE_ID) REFERENCES GRESTLER_VERTEX_TYPE(ID);

-- Constraints
ALTER TABLE GRESTLER_VERTEX_TYPE ADD CONSTRAINT UQ_GRESTLER_VERTEX_TYPE__NAME
    UNIQUE (NAME);

-- Generic base vertex type
INSERT INTO GRESTLER_VERTEX_TYPE
            ( ID, NAME, SUPER_TYPE_ID )
     VALUES ( '00000000-7a26-11e4-a545-08002741a702', 'Vertex', '00000000-7a26-11e4-a545-08002741a702' );


---------------
-- Edge Type --
---------------

-- Table
CREATE TABLE GRESTLER_EDGE_TYPE (
    ID UUID NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    SUPER_TYPE_ID UUID NOT NULL,
    FROM_VERTEX_TYPE_ID UUID NOT NULL,
    TO_VERTEX_TYPE_ID UUID NOT NULL
);

-- Primary key
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT PK_GRESTLER_EDGE_TYPE
    PRIMARY KEY (ID);

-- Foreign keys
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT FK_GRESTLER_EDGE_TYPE__SUPER_TYPE
    FOREIGN KEY (SUPER_TYPE_ID) REFERENCES GRESTLER_EDGE_TYPE(ID);
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT FK_GRESTLER_EDGE_TYPE__FROM_VERTEX_TYPE
    FOREIGN KEY (FROM_VERTEX_TYPE_ID) REFERENCES GRESTLER_VERTEX_TYPE(ID);
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT FK_GRESTLER_EDGE_TYPE__TO_VERTEX_TYPE
    FOREIGN KEY (TO_VERTEX_TYPE_ID) REFERENCES GRESTLER_VERTEX_TYPE(ID);

-- Constraints
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT UQ_GRESTLER_EDGE_TYPE__NAME
    UNIQUE (NAME);

-- Generic base edge type
INSERT INTO GRESTLER_EDGE_TYPE
            ( ID, NAME, SUPER_TYPE_ID, FROM_VERTEX_TYPE_ID, TO_VERTEX_TYPE_ID )
     VALUES ( '00000001-7a26-11e4-a545-08002741a702', 'Edge', '00000001-7a26-11e4-a545-08002741a702',
              '00000000-7a26-11e4-a545-08002741a702', '00000000-7a26-11e4-a545-08002741a702' );


