
-----------------
-- Vertex Type --
-----------------

-- Table
CREATE TABLE GRESTLER_VERTEX_TYPE (
    ID UUID NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    BASE_TYPE_ID UUID NOT NULL
);

-- Primary key
ALTER TABLE GRESTLER_VERTEX_TYPE ADD CONSTRAINT PK_GRESTLER_VERTEX_TYPE
    PRIMARY KEY (ID);

-- Foreign keys
ALTER TABLE GRESTLER_VERTEX_TYPE ADD CONSTRAINT FK_GRESTLER_VERTEX_TYPE__BASE_TYPE
    FOREIGN KEY (BASE_TYPE_ID) REFERENCES GRESTLER_VERTEX_TYPE(ID);

-- Generic base vertex type
INSERT INTO GRESTLER_VERTEX_TYPE
            ( ID, NAME, BASE_TYPE_ID )
     VALUES ( 'cde94400-7a26-11e4-a545-08002741a702', 'Vertex', 'cde94400-7a26-11e4-a545-08002741a702' );


---------------
-- Edge Type --
---------------

-- Table
CREATE TABLE GRESTLER_EDGE_TYPE (
    ID UUID NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    BASE_TYPE_ID UUID NOT NULL,
    FROM_VERTEX_TYPE_ID UUID NOT NULL,
    TO_VERTEX_TYPE_ID UUID NOT NULL
);

-- Primary key
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT PK_GRESTLER_EDGE_TYPE
    PRIMARY KEY (ID);

-- Foreign keys
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT FK_GRESTLER_EDGE_TYPE__BASE_TYPE
    FOREIGN KEY (BASE_TYPE_ID) REFERENCES GRESTLER_EDGE_TYPE(ID);
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT FK_GRESTLER_EDGE_TYPE__FROM_VERTEX_TYPE
    FOREIGN KEY (FROM_VERTEX_TYPE_ID) REFERENCES GRESTLER_VERTEX_TYPE(ID);
ALTER TABLE GRESTLER_EDGE_TYPE ADD CONSTRAINT FK_GRESTLER_EDGE_TYPE__TO_VERTEX_TYPE
    FOREIGN KEY (TO_VERTEX_TYPE_ID) REFERENCES GRESTLER_VERTEX_TYPE(ID);

-- Generic base edge type
INSERT INTO GRESTLER_EDGE_TYPE
            ( ID, NAME, BASE_TYPE_ID, FROM_VERTEX_TYPE_ID, TO_VERTEX_TYPE_ID )
     VALUES ( 'cde94401-7a26-11e4-a545-08002741a702', 'Edge', 'cde94401-7a26-11e4-a545-08002741a702',
              'cde94400-7a26-11e4-a545-08002741a702', 'cde94400-7a26-11e4-a545-08002741a702' );


